name: eyh
channels:
    - conda-forge
dependencies:
    - python
    - numpy
    - jupyter
    - opencv3
    - matplotlib
    - pillow
    - ipywidgets
    - widgetsnbextension
    - ffmpeg
    - imageio
    - pip:
        - moviepy
