name: eyh
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - jupyter
    - opencv3
    - matplotlib
    - pillow
    - ipywidgets
    - widgetsnbextension
    - ffmpeg
    - imageio=2.1.2
    - pip:
        - moviepy
        - --no-deps
